{
	"name": "сгенерил Clab",
	"scripts": [
		{
			"scriptName": "Нечетное отправление по Н2 с 2П пути на 2ПП",
			"scriptKey": "275",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0332:0:00:8ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0333:0:01:8МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0308:0:00:2ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0309:0:01:2МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				}
			]
		},
		{
			"scriptName": "Нечетное отправление по Н2 с 2П пути на 1УП",
			"scriptKey": "271",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0332:0:00:8ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0333:0:01:8МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0324:0:00:6ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0325:0:01:6МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				}
			]
		},
		{
			"scriptName": "Нечетное отправление по Н4 с 4П пути на 2ПП",
			"scriptKey": "276",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0308:0:00:2ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0309:0:01:2МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0376:0:00:20ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0377:0:01:20МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0316:0:00:4ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0317:0:01:4МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Нечетное отправление по Н3 с 3П пути на 1УП",
			"scriptKey": "269",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0324:0:00:6ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0325:0:01:6МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0408:0:00:36ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0409:0:01:36МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0404:0:00:34ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0405:0:01:34МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				}
			]
		},
		{
			"scriptName": "Нечетное отправление по Н3 с 3П пути на 2ПП",
			"scriptKey": "273",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0332:0:00:8ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0333:0:01:8МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0308:0:00:2ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0309:0:01:2МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0408:0:00:36ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0409:0:01:36МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0404:0:00:34ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0405:0:01:34МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Нечетное отправление по Н1 с 1П пути на 1УП",
			"scriptKey": "268",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0324:0:00:6ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0325:0:01:6МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				}
			]
		},
		{
			"scriptName": "Нечетное отправление по Н1 с 1П пути на 2ПП",
			"scriptKey": "272",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0332:0:00:8ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0333:0:01:8МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0308:0:00:2ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0309:0:01:2МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Нечетное отправление по Н6 с 6П пути на 2ПП",
			"scriptKey": "277",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0308:0:00:2ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0309:0:01:2МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0316:0:00:4ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0317:0:01:4МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0384:0:00:24ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0385:0:01:24МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Нечетное отправление по Н5 с 5П пути на 1УП",
			"scriptKey": "270",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0324:0:00:6ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0325:0:01:6МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0408:0:00:36ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0409:0:01:36МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0404:0:00:34ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0405:0:01:34МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				}
			]
		},
		{
			"scriptName": "Нечетное отправление по Н5 с 5П пути на 2ПП",
			"scriptKey": "274",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0332:0:00:8ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0333:0:01:8МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0308:0:00:2ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0309:0:01:2МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0408:0:00:36ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0409:0:01:36МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0404:0:00:34ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0405:0:01:34МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Передача по Нм1А с 1АП пути на 1П путь",
			"scriptKey": "292",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0336:0:00:9ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0337:0:01:9МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0360:0:00:15ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0361:0:01:15МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Передача по Нм1А с 1АП пути на 3П путь",
			"scriptKey": "296",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0336:0:00:9ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0337:0:01:9МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0360:0:00:15ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0361:0:01:15МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0368:0:00:17ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0369:0:01:17МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0428:0:00:46ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0429:0:01:46МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Передача по Нм1А с 1АП пути на 5П путь",
			"scriptKey": "297",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0336:0:00:9ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0337:0:01:9МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0360:0:00:15ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0361:0:01:15МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0368:0:00:17ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0369:0:01:17МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0428:0:00:46ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0429:0:01:46МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0424:0:00:44ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0425:0:01:44МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Передача по НМ1А с 1АП пути на 2П путь",
			"scriptKey": "293",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0344:0:00:11ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0345:0:01:11МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0336:0:00:9ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0337:0:01:9МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0420:0:00:42ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0421:0:01:42МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Передача по НМ1В с 1ВП пути на 1АП путь",
			"scriptKey": "291",
			"steps": [
			]
		},
		{
			"scriptName": "Нечетный прием по Н с 1ПП на 1ВП путь",
			"scriptKey": "280",
			"steps": [
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0328:0:00:7ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0329:0:01:7МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Нечетный прием по Нд с 2УП на 2ВП путь",
			"scriptKey": "281",
			"steps": [
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				}
			]
		},
		{
			"scriptName": "Передача по ЧМ2 с 2П пути на 2АП путь",
			"scriptKey": "285",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0420:0:00:42ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0421:0:01:42МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Передача по ЧМ4 с 4П пути на 2АП путь",
			"scriptKey": "286",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0420:0:00:42ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0421:0:01:42МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0436:0:00:4СБПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0437:0:01:4СБМК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0416:0:00:40ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0417:0:01:40МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Передача по ЧМ3 с 3П пути на 1ВП путь",
			"scriptKey": "283",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0336:0:00:9ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0337:0:01:9МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0360:0:00:15ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0361:0:01:15МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0368:0:00:17ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0369:0:01:17МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0428:0:00:46ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0429:0:01:46МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Передача по ЧМ1 с 1П пути на 1ВП путь",
			"scriptKey": "282",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0336:0:00:9ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0337:0:01:9МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0360:0:00:15ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0361:0:01:15МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Передача по ЧМ6 с 6П пути на 2АП путь",
			"scriptKey": "287",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0344:0:00:11ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0345:0:01:11МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0420:0:00:42ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0421:0:01:42МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0416:0:00:40ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0417:0:01:40МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0440:0:00:6СБПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0441:0:01:6СБМК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0412:0:00:38ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0413:0:01:38МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Передача по ЧМ5 с 5П пути на 1ВП путь",
			"scriptKey": "284",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0336:0:00:9ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0337:0:01:9МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0360:0:00:15ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0361:0:01:15МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0368:0:00:17ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0369:0:01:17МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0428:0:00:46ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0429:0:01:46МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0424:0:00:44ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0425:0:01:44МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Передача по ЧМ2А с 2АП пути на 2ВП путь",
			"scriptKey": "289",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0344:0:00:11ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0345:0:01:11МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Передача по ЧМ2А с 2АП пути на 1ВП путь",
			"scriptKey": "290",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0344:0:00:11ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0345:0:01:11МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0336:0:00:9ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0337:0:01:9МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Передача по ЧМ8 с 8П пути на 2АП путь",
			"scriptKey": "288",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0420:0:00:42ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0421:0:01:42МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0416:0:00:40ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0417:0:01:40МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0412:0:00:38ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0413:0:01:38МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0444:0:00:8СБПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0445:0:01:8СБМК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Четное отправление по Ч2В с 2ВП пути на 2УП",
			"scriptKey": "279",
			"steps": [
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				}
			]
		},
		{
			"scriptName": "Четное отправление по Ч1В с 1ВП пути на 1ПП",
			"scriptKey": "278",
			"steps": [
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0328:0:00:7ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0329:0:01:7МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Четный прием по Чд с 1УП на 1П путь",
			"scriptKey": "264",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0324:0:00:6ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0325:0:01:6МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				}
			]
		},
		{
			"scriptName": "Четный прием по Чд с 1УП на 3П путь",
			"scriptKey": "265",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0324:0:00:6ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0325:0:01:6МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0408:0:00:36ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0409:0:01:36МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0404:0:00:34ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0405:0:01:34МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				}
			]
		},
		{
			"scriptName": "Четный прием по Чд с 1УП на 5П путь",
			"scriptKey": "266",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0324:0:00:6ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0325:0:01:6МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0408:0:00:36ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0409:0:01:36МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0404:0:00:34ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0405:0:01:34МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				}
			]
		},
		{
			"scriptName": "Четный прием по Чд с 1УП на 2П путь",
			"scriptKey": "267",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0332:0:00:8ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0333:0:01:8МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0324:0:00:6ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0325:0:01:6МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				}
			]
		},
		{
			"scriptName": "Четный прием по Ч с 2ПП на 2П путь",
			"scriptKey": "260",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0332:0:00:8ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0333:0:01:8МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0308:0:00:2ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0309:0:01:2МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				}
			]
		},
		{
			"scriptName": "Четный прием по Ч с 2ПП на 1П путь",
			"scriptKey": "257",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0332:0:00:8ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0333:0:01:8МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0308:0:00:2ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0309:0:01:2МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Четный прием по Ч с 2ПП на 3П путь",
			"scriptKey": "258",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0332:0:00:8ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0333:0:01:8МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0308:0:00:2ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0309:0:01:2МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0408:0:00:36ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0409:0:01:36МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0404:0:00:34ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0405:0:01:34МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Четный прием по Ч с 2ПП на 5П путь",
			"scriptKey": "259",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0332:0:00:8ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0333:0:01:8МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0308:0:00:2ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0309:0:01:2МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0408:0:00:36ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0409:0:01:36МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0404:0:00:34ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0405:0:01:34МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Четный прием по Ч с 2ПП на 4П путь",
			"scriptKey": "261",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0308:0:00:2ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0309:0:01:2МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0376:0:00:20ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0377:0:01:20МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0316:0:00:4ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0317:0:01:4МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Четный прием по Ч с 2ПП на 6П путь",
			"scriptKey": "262",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0308:0:00:2ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0309:0:01:2МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0316:0:00:4ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0317:0:01:4МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0384:0:00:24ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0385:0:01:24МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Четный прием по Ч с 2ПП на 8П путь",
			"scriptKey": "263",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0308:0:00:2ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0309:0:01:2МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0316:0:00:4ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0317:0:01:4МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0384:0:00:24ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0385:0:01:24МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Передача по НМ1А с 1АП пути на 4П путь",
			"scriptKey": "294",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0344:0:00:11ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0345:0:01:11МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0336:0:00:9ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0337:0:01:9МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0420:0:00:42ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0421:0:01:42МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0436:0:00:4СБПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0437:0:01:4СБМК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0416:0:00:40ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0417:0:01:40МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Передача по НМ1А с 1АП пути на 6П путь",
			"scriptKey": "295",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0344:0:00:11ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0345:0:01:11МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0336:0:00:9ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0337:0:01:9МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0420:0:00:42ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0421:0:01:42МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0416:0:00:40ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0417:0:01:40МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0440:0:00:6СБПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0441:0:01:6СБМК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0412:0:00:38ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0413:0:01:38МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Передача по НМ2Б с 2БП пути на 2П путь",
			"scriptKey": "298",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0344:0:00:11ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0345:0:01:11МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0420:0:00:42ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0421:0:01:42МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Передача по НМ2Б с 2БП пути на 4П путь",
			"scriptKey": "299",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0344:0:00:11ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0345:0:01:11МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0420:0:00:42ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0421:0:01:42МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0436:0:00:4СБПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0437:0:01:4СБМК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0416:0:00:40ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0417:0:01:40МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Передача по НМ2Б с 2БП пути на 6П путь",
			"scriptKey": "300",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0344:0:00:11ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0345:0:01:11МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0420:0:00:42ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0421:0:01:42МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0416:0:00:40ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0417:0:01:40МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0440:0:00:6СБПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0441:0:01:6СБМК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0412:0:00:38ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0413:0:01:38МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Четный прием по Ч с 2ПП на 1П путь (-2)",
			"scriptKey": "301",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0308:0:00:2ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0309:0:01:2МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0376:0:00:20ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0377:0:01:20МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0316:0:00:4ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0317:0:01:4МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Четный прием по Ч с 2ПП на 3П путь (-2)",
			"scriptKey": "302",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0308:0:00:2ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0309:0:01:2МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0376:0:00:20ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0377:0:01:20МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0316:0:00:4ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0317:0:01:4МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Четный прием по Ч с 2ПП на 5П путь (-2)",
			"scriptKey": "303",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0308:0:00:2ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0309:0:01:2МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0376:0:00:20ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0377:0:01:20МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0316:0:00:4ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0317:0:01:4МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0408:0:00:36ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0409:0:01:36МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0404:0:00:34ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0405:0:01:34МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Четный прием по Ч с 2ПП на 2П путь (-2)",
			"scriptKey": "304",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0308:0:00:2ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0309:0:01:2МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0376:0:00:20ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0377:0:01:20МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0316:0:00:4ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0317:0:01:4МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Четный прием по ЧД с 1УП на 1П путь (-6)",
			"scriptKey": "305",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0332:0:00:8ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0333:0:01:8МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0324:0:00:6ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0325:0:01:6МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Четный прием по ЧД с 1УП на 3П путь (-6)",
			"scriptKey": "306",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0332:0:00:8ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0333:0:01:8МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0324:0:00:6ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0325:0:01:6МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0408:0:00:36ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0409:0:01:36МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0404:0:00:34ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0405:0:01:34МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Четный прием по ЧД с 1УП на 5П путь (-6)",
			"scriptKey": "307",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0332:0:00:8ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0333:0:01:8МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0324:0:00:6ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0325:0:01:6МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0408:0:00:36ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0409:0:01:36МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0404:0:00:34ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0405:0:01:34МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Нечетное отправление по Н1 с 1П пути на 1УП (-28)",
			"scriptKey": "308",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0332:0:00:8ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0333:0:01:8МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0324:0:00:6ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0325:0:01:6МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Нечетное отправление по Н3 с 3П пути на 1УП (-28)",
			"scriptKey": "309",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0332:0:00:8ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0333:0:01:8МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0324:0:00:6ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0325:0:01:6МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0408:0:00:36ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0409:0:01:36МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0404:0:00:34ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0405:0:01:34МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Нечетное отправление по Н5 с 5П пути на 1УП (-28)",
			"scriptKey": "310",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0332:0:00:8ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0333:0:01:8МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0324:0:00:6ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0325:0:01:6МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0408:0:00:36ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0409:0:01:36МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0404:0:00:34ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0405:0:01:34МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Нечетное отправление по Н1 с 1П пути на 2ПП (-22)",
			"scriptKey": "311",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0308:0:00:2ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0309:0:01:2МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0376:0:00:20ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0377:0:01:20МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0316:0:00:4ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0317:0:01:4МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Нечетное отправление по Н3 с 3П пути на 2ПП (-22)",
			"scriptKey": "312",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0308:0:00:2ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0309:0:01:2МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0376:0:00:20ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0377:0:01:20МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0316:0:00:4ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0317:0:01:4МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0408:0:00:36ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0409:0:01:36МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0404:0:00:34ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0405:0:01:34МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Нечетное отправление по Н5 с 5П пути на 2ПП (-22)",
			"scriptKey": "313",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0308:0:00:2ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0309:0:01:2МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0376:0:00:20ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0377:0:01:20МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0316:0:00:4ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0317:0:01:4МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0408:0:00:36ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0409:0:01:36МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0404:0:00:34ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0405:0:01:34МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "Нечетное отправление по Н2 с 2П пути на 2ПП (-22)",
			"scriptKey": "314",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0308:0:00:2ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0309:0:01:2МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0376:0:00:20ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0377:0:01:20МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0316:0:00:4ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0317:0:01:4МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору Н2 до светофора М22",
			"scriptKey": "869",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору Н2 до светофора М6",
			"scriptKey": "870",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0376:0:00:20ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0377:0:01:20МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				}
			]
		},
		{
			"scriptName": "По светофору Н2 за светофор М10",
			"scriptKey": "871",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0376:0:00:20ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0377:0:01:20МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0340:0:00:10ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0341:0:01:10МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору Н2 за светофор М12",
			"scriptKey": "872",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0376:0:00:20ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0377:0:01:20МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0340:0:00:10ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0341:0:01:10МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору Н4 до светофора М6",
			"scriptKey": "873",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0376:0:00:20ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0377:0:01:20МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				}
			]
		},
		{
			"scriptName": "По светофору Н4 за светофор М10",
			"scriptKey": "874",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0376:0:00:20ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0377:0:01:20МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0340:0:00:10ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0341:0:01:10МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору Н4 за светофор М12",
			"scriptKey": "875",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0376:0:00:20ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0377:0:01:20МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0340:0:00:10ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0341:0:01:10МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору Н3 за светофор М30",
			"scriptKey": "856",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0408:0:00:36ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0409:0:01:36МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0404:0:00:34ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0405:0:01:34МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0396:0:00:30ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0397:0:01:30МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору Н3 до светофора М14",
			"scriptKey": "857",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0408:0:00:36ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0409:0:01:36МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0404:0:00:34ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0405:0:01:34МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				}
			]
		},
		{
			"scriptName": "По светофору Н3 за светофор М28",
			"scriptKey": "855",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0408:0:00:36ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0409:0:01:36МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0404:0:00:34ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0405:0:01:34МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0396:0:00:30ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0397:0:01:30МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору Н3 до светофора М22",
			"scriptKey": "858",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0408:0:00:36ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0409:0:01:36МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0404:0:00:34ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0405:0:01:34МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору Н3 до светофора М6",
			"scriptKey": "859",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0376:0:00:20ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0377:0:01:20МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0408:0:00:36ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0409:0:01:36МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0404:0:00:34ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0405:0:01:34МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору Н3 за светофор М10",
			"scriptKey": "860",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0376:0:00:20ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0377:0:01:20МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0408:0:00:36ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0409:0:01:36МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0404:0:00:34ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0405:0:01:34МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0340:0:00:10ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0341:0:01:10МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору Н3 за светофор М12",
			"scriptKey": "861",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0376:0:00:20ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0377:0:01:20МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0408:0:00:36ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0409:0:01:36МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0404:0:00:34ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0405:0:01:34МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0340:0:00:10ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0341:0:01:10МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору Н1 до светофора М14",
			"scriptKey": "850",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				}
			]
		},
		{
			"scriptName": "По светофору Н1 до светофора М22",
			"scriptKey": "851",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору Н1 до светофора М6",
			"scriptKey": "852",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0376:0:00:20ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0377:0:01:20МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору Н1 за светофор М10",
			"scriptKey": "853",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0376:0:00:20ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0377:0:01:20МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0340:0:00:10ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0341:0:01:10МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору Н1 за светофор М12",
			"scriptKey": "854",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0376:0:00:20ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0377:0:01:20МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0340:0:00:10ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0341:0:01:10МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору Н6 за светофор М16",
			"scriptKey": "879",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0384:0:00:24ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0385:0:01:24МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0348:0:00:12ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0349:0:01:12МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				}
			]
		},
		{
			"scriptName": "По светофору Н6 до светофора М6",
			"scriptKey": "876",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0384:0:00:24ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0385:0:01:24МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору Н6 за светофор М10",
			"scriptKey": "877",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0384:0:00:24ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0385:0:01:24МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0340:0:00:10ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0341:0:01:10МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору Н6 за светофор М12",
			"scriptKey": "878",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0384:0:00:24ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0385:0:01:24МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0340:0:00:10ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0341:0:01:10МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору Н5 за светофор М30",
			"scriptKey": "863",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0408:0:00:36ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0409:0:01:36МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0404:0:00:34ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0405:0:01:34МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0396:0:00:30ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0397:0:01:30МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору Н5 до светофора М14",
			"scriptKey": "864",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0408:0:00:36ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0409:0:01:36МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0404:0:00:34ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0405:0:01:34МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				}
			]
		},
		{
			"scriptName": "По светофору Н5 за светофор М28",
			"scriptKey": "862",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0408:0:00:36ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0409:0:01:36МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0404:0:00:34ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0405:0:01:34МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0396:0:00:30ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0397:0:01:30МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору Н5 до светофора М22",
			"scriptKey": "865",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0408:0:00:36ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0409:0:01:36МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0404:0:00:34ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0405:0:01:34МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору Н5 до светофора М6",
			"scriptKey": "866",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0376:0:00:20ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0377:0:01:20МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0408:0:00:36ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0409:0:01:36МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0404:0:00:34ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0405:0:01:34МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору Н5 за светофор М10",
			"scriptKey": "867",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0376:0:00:20ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0377:0:01:20МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0408:0:00:36ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0409:0:01:36МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0404:0:00:34ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0405:0:01:34МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0340:0:00:10ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0341:0:01:10МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору Н5 за светофор М12",
			"scriptKey": "868",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0376:0:00:20ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0377:0:01:20МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0408:0:00:36ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0409:0:01:36МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0404:0:00:34ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0405:0:01:34МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0340:0:00:10ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0341:0:01:10МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М34 на 2П путь",
			"scriptKey": "841",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0420:0:00:42ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0421:0:01:42МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М34 на 4П путь",
			"scriptKey": "842",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0420:0:00:42ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0421:0:01:42МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0436:0:00:4СБПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0437:0:01:4СБМК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0416:0:00:40ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0417:0:01:40МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М34 на 6П путь",
			"scriptKey": "843",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0420:0:00:42ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0421:0:01:42МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0416:0:00:40ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0417:0:01:40МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0440:0:00:6СБПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0441:0:01:6СБМК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0412:0:00:38ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0413:0:01:38МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М34 на 8П путь",
			"scriptKey": "844",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0420:0:00:42ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0421:0:01:42МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0416:0:00:40ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0417:0:01:40МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0412:0:00:38ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0413:0:01:38МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0444:0:00:8СБПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0445:0:01:8СБМК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М24 за светофор М16",
			"scriptKey": "834",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0384:0:00:24ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0385:0:01:24МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0348:0:00:12ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0349:0:01:12МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				}
			]
		},
		{
			"scriptName": "По светофору М24 до светофора М6",
			"scriptKey": "831",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0384:0:00:24ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0385:0:01:24МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М24 за светофор М10",
			"scriptKey": "832",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0384:0:00:24ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0385:0:01:24МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0340:0:00:10ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0341:0:01:10МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М24 за светофор М12",
			"scriptKey": "833",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0384:0:00:24ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0385:0:01:24МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0340:0:00:10ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0341:0:01:10МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М38 на 3П путь",
			"scriptKey": "847",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0428:0:00:46ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0429:0:01:46МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М38 на 5П путь",
			"scriptKey": "848",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0428:0:00:46ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0429:0:01:46МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0424:0:00:44ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0425:0:01:44МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М38 за светофор М36",
			"scriptKey": "849",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0428:0:00:46ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0429:0:01:46МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0424:0:00:44ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0425:0:01:44МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М22 за светофор М4",
			"scriptKey": "829",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0332:0:00:8ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0333:0:01:8МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0308:0:00:2ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0309:0:01:2МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				}
			]
		},
		{
			"scriptName": "По светофору М22 за светофор М8",
			"scriptKey": "830",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0332:0:00:8ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0333:0:01:8МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0324:0:00:6ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0325:0:01:6МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				}
			]
		},
		{
			"scriptName": "По светофору М3 до светофора М7",
			"scriptKey": "771",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0304:0:00:1/3ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0305:0:01:1/3МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору ЧМ4 до светофора ЧМ2А",
			"scriptKey": "784",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0420:0:00:42ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0421:0:01:42МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0436:0:00:4СБПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0437:0:01:4СБМК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0416:0:00:40ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0417:0:01:40МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М16 на 6П путь",
			"scriptKey": "820",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0384:0:00:24ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0385:0:01:24МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0348:0:00:12ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0349:0:01:12МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М16 на 8П путь",
			"scriptKey": "821",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0384:0:00:24ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0385:0:01:24МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0348:0:00:12ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0349:0:01:12МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М26 на 1П путь",
			"scriptKey": "835",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М26 до светофора М32",
			"scriptKey": "836",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0404:0:00:34ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0405:0:01:34МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М1 за светофор М5",
			"scriptKey": "769",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0304:0:00:1/3ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0305:0:01:1/3МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М1 до светофора М7",
			"scriptKey": "770",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0304:0:00:1/3ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0305:0:01:1/3МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0304:0:00:1/3ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0305:0:01:1/3МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М5 за светофор М1",
			"scriptKey": "772",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0304:0:00:1/3ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0305:0:01:1/3МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М7 до светофора НМ1В",
			"scriptKey": "773",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0328:0:00:7ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0329:0:01:7МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0320:0:00:5ССПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0321:0:01:5ССМК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М9 до светофора НМ1В",
			"scriptKey": "774",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0328:0:00:7ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0329:0:01:7МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М11 до светофора Ч1В",
			"scriptKey": "775",
			"steps": [
			]
		},
		{
			"scriptName": "По светофору М13 до светофора М38",
			"scriptKey": "776",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0368:0:00:17ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0369:0:01:17МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0352:0:00:13ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0353:0:01:13МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М15 до светофора М11",
			"scriptKey": "777",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0336:0:00:9ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0337:0:01:9МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору ЧМ1 до светофора М15",
			"scriptKey": "778",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0360:0:00:15ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0361:0:01:15МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору ЧМ3 на М13П путь",
			"scriptKey": "779",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0368:0:00:17ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0369:0:01:17МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0428:0:00:46ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0429:0:01:46МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0352:0:00:13ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0353:0:01:13МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				}
			]
		},
		{
			"scriptName": "По светофору ЧМ3 до светофора М15",
			"scriptKey": "780",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0360:0:00:15ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0361:0:01:15МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0368:0:00:17ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0369:0:01:17МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0428:0:00:46ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0429:0:01:46МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору ЧМ5 на М13П путь",
			"scriptKey": "781",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0368:0:00:17ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0369:0:01:17МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0428:0:00:46ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0429:0:01:46МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0352:0:00:13ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0353:0:01:13МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				}
			]
		},
		{
			"scriptName": "По светофору ЧМ5 до светофора М15",
			"scriptKey": "782",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0360:0:00:15ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0361:0:01:15МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0368:0:00:17ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0369:0:01:17МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0428:0:00:46ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0429:0:01:46МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору ЧМ2 до светофора ЧМ2А",
			"scriptKey": "783",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0420:0:00:42ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0421:0:01:42МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору ЧМ6 до светофора ЧМ2А",
			"scriptKey": "785",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0420:0:00:42ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0421:0:01:42МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0416:0:00:40ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0417:0:01:40МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0440:0:00:6СБПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0441:0:01:6СБМК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0412:0:00:38ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0413:0:01:38МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору ЧМ8 до светофора ЧМ2А",
			"scriptKey": "786",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0420:0:00:42ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0421:0:01:42МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0416:0:00:40ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0417:0:01:40МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0412:0:00:38ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0413:0:01:38МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0444:0:00:8СБПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0445:0:01:8СБМК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору ЧМ2А до светофора М11",
			"scriptKey": "787",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0344:0:00:11ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0345:0:01:11МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0336:0:00:9ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0337:0:01:9МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору Ч1В за светофор М1",
			"scriptKey": "788",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0328:0:00:7ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0329:0:01:7МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0320:0:00:5ССПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0321:0:01:5ССМК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0304:0:00:1/3ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0305:0:01:1/3МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0304:0:00:1/3ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0305:0:01:1/3МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору Ч1В за светофор М3",
			"scriptKey": "789",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0328:0:00:7ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0329:0:01:7МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0320:0:00:5ССПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0321:0:01:5ССМК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0304:0:00:1/3ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0305:0:01:1/3МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору Ч1В за светофор М9",
			"scriptKey": "790",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0328:0:00:7ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0329:0:01:7МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору НМ1В до светофора НМ1А",
			"scriptKey": "791",
			"steps": [
			]
		},
		{
			"scriptName": "По светофору НМ1А до светофора М38",
			"scriptKey": "792",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0336:0:00:9ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0337:0:01:9МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0360:0:00:15ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0361:0:01:15МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0368:0:00:17ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0369:0:01:17МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору НМ1А до светофора М34",
			"scriptKey": "793",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0344:0:00:11ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0345:0:01:11МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0336:0:00:9ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0337:0:01:9МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору НМ1А на 1П путь",
			"scriptKey": "794",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0336:0:00:9ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0337:0:01:9МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0360:0:00:15ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0361:0:01:15МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М2 до светофора М18",
			"scriptKey": "795",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0316:0:00:4ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0317:0:01:4МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М4 до светофора М18",
			"scriptKey": "796",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0308:0:00:2ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0309:0:01:2МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0316:0:00:4ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0317:0:01:4МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М4 на 1П путь",
			"scriptKey": "797",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0332:0:00:8ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0333:0:01:8МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0308:0:00:2ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0309:0:01:2МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М4 на 2П путь",
			"scriptKey": "798",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0332:0:00:8ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0333:0:01:8МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0308:0:00:2ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0309:0:01:2МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М4 до светофора М32",
			"scriptKey": "799",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0332:0:00:8ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0333:0:01:8МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0308:0:00:2ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0309:0:01:2МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0404:0:00:34ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0405:0:01:34МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М6 за светофор М2",
			"scriptKey": "800",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0316:0:00:4ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0317:0:01:4МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М6 за светофор М4",
			"scriptKey": "801",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0308:0:00:2ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0309:0:01:2МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0316:0:00:4ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0317:0:01:4МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М8 до светофора М26",
			"scriptKey": "802",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0324:0:00:6ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0325:0:01:6МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				}
			]
		},
		{
			"scriptName": "По светофору М8 на 1П путь",
			"scriptKey": "803",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0324:0:00:6ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0325:0:01:6МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				}
			]
		},
		{
			"scriptName": "По светофору М8 на 2П путь",
			"scriptKey": "804",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0332:0:00:8ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0333:0:01:8МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0324:0:00:6ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0325:0:01:6МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М8 до светофора М32",
			"scriptKey": "805",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0324:0:00:6ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0325:0:01:6МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0404:0:00:34ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0405:0:01:34МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				}
			]
		},
		{
			"scriptName": "По светофору М10 до светофора М32",
			"scriptKey": "806",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0376:0:00:20ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0377:0:01:20МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0404:0:00:34ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0405:0:01:34МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0340:0:00:10ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0341:0:01:10МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М10 на 1П путь",
			"scriptKey": "807",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0376:0:00:20ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0377:0:01:20МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0340:0:00:10ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0341:0:01:10МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М10 на 2П путь",
			"scriptKey": "808",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0376:0:00:20ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0377:0:01:20МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0340:0:00:10ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0341:0:01:10МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М10 на 4П путь",
			"scriptKey": "809",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0376:0:00:20ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0377:0:01:20МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0340:0:00:10ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0341:0:01:10МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М10 на 6П путь",
			"scriptKey": "810",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0384:0:00:24ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0385:0:01:24МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0340:0:00:10ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0341:0:01:10МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М10 на 8П путь",
			"scriptKey": "811",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0384:0:00:24ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0385:0:01:24МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0340:0:00:10ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0341:0:01:10МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М12 до светофора М32",
			"scriptKey": "812",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0376:0:00:20ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0377:0:01:20МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0404:0:00:34ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0405:0:01:34МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0340:0:00:10ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0341:0:01:10МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М12 на 1П путь",
			"scriptKey": "813",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0376:0:00:20ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0377:0:01:20МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0340:0:00:10ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0341:0:01:10МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М12 на 2П путь",
			"scriptKey": "814",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0376:0:00:20ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0377:0:01:20МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0340:0:00:10ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0341:0:01:10МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М12 на 4П путь",
			"scriptKey": "815",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0376:0:00:20ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0377:0:01:20МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0340:0:00:10ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0341:0:01:10МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М12 на 6П путь",
			"scriptKey": "816",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0384:0:00:24ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0385:0:01:24МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0340:0:00:10ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0341:0:01:10МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М12 на 8П путь",
			"scriptKey": "817",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0384:0:00:24ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0385:0:01:24МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0340:0:00:10ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0341:0:01:10МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М14 за светофор М8",
			"scriptKey": "818",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0324:0:00:6ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0325:0:01:6МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				}
			]
		},
		{
			"scriptName": "По светофору М16 за светофор М20",
			"scriptKey": "819",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0348:0:00:12ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0349:0:01:12МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				}
			]
		},
		{
			"scriptName": "По светофору М18 до светофора М32",
			"scriptKey": "822",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0376:0:00:20ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0377:0:01:20МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0404:0:00:34ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0405:0:01:34МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М18 на 1П путь",
			"scriptKey": "823",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0376:0:00:20ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0377:0:01:20МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0400:0:00:32ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0401:0:01:32МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0392:0:00:28ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0393:0:01:28МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М18 на 2П путь",
			"scriptKey": "824",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0388:0:00:26ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0389:0:01:26МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0380:0:00:22ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0381:0:01:22МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0376:0:00:20ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0377:0:01:20МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М18 на 4П путь",
			"scriptKey": "825",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0376:0:00:20ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0377:0:01:20МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М18 на 6П путь",
			"scriptKey": "826",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0384:0:00:24ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0385:0:01:24МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М18 на 8П путь",
			"scriptKey": "827",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0356:0:00:14ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0357:0:01:14МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0384:0:00:24ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0385:0:01:24МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0364:0:00:16/18ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0365:0:01:16/18МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М20 за светофор М16",
			"scriptKey": "828",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0348:0:00:12ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0349:0:01:12МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				}
			]
		},
		{
			"scriptName": "По светофору М28 до светофора М32",
			"scriptKey": "837",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0404:0:00:34ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0405:0:01:34МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0396:0:00:30ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0397:0:01:30МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М30 до светофора М32",
			"scriptKey": "838",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0404:0:00:34ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0405:0:01:34МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0396:0:00:30ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0397:0:01:30МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М32 на 3П путь",
			"scriptKey": "839",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0408:0:00:36ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0409:0:01:36МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М32 на 5П путь",
			"scriptKey": "840",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0408:0:00:36ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0409:0:01:36МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М36 до светофора М15",
			"scriptKey": "845",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0360:0:00:15ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0361:0:01:15МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0368:0:00:17ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0369:0:01:17МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0428:0:00:46ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0429:0:01:46МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0424:0:00:44ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0425:0:01:44МК"
						}
					]
				}
			]
		},
		{
			"scriptName": "По светофору М36 за светофор М13",
			"scriptKey": "846",
			"steps": [
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0368:0:00:17ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0369:0:01:17МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0428:0:00:46ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0429:0:01:46МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0424:0:00:44ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0425:0:01:44МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0352:0:00:13ПК"
						},
						{
							"cmd": "tssrv_setbits",
							"ts_full": "SEIMA#1:0353:0:01:13МК"
						}
					]
				},
				{
					"wait": 50,
					"commands": [
					]
				}
			]
		}
	]
}
